  version: '2'

  services:
    mysql:
      image: mysql:8.0
      container_name: mysql-server-80
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - ./mysql-dump:/docker-entrypoint-initdb.d
        - ./db:/var/lib/mysql:rw
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=root
      ports:
        - "3306:3306"
    website:
      container_name: php73
      build: . #Dockerfile
      volumes:
        - ../:/var/www/html
      ports:
        - "80:80"
      links:
        - mysql
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - mysql
      ports:
        - '8080:80' # via localhost:8080 opent phpmyadmin
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
        MYSQL_ROOT_PASSWORD: root

#  docker exec -it mysql-server-80  bash -l om via cli met server te verbinden
# mysql -u root -p om via cli te verbinden met mysql
# docker ps -a
